# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=100)),
                ('team_logo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='YearStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passingyards', models.IntegerField(max_length=10)),
                ('rushingyards', models.IntegerField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
