# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearstats',
            name='passingyards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yearstats',
            name='rushingyards',
            field=models.IntegerField(),
        ),
    ]
