# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20171103_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearstats',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
