# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_yearstats_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearstats',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
